### PR TITLE
Add IPv6 support (command-line and tuntap)

### PR DESCRIPTION
**Pull request by deavmi**
## Purpose :writing_hand: 

Add IPv6 support.

### Issues

- [x] tuntap refuses (even tested with `ip addr add <v6addr> dev tnc0` to accept IPv6 addresses
- [x] command-line parsing
- [x] driver code (tuntap)
- [x] code review // clean up // safety checks // error handling

### CODE REVIEW

**Comment by deavmi** [comment]
Progressing with most of what I can for adding Ipv6 to `tncattach`, all the code is done. Just need to bug fix. For some reason the interface tuntap interface being brought up gives "INVALID ARGUMENT" when trying to add the v6 address; but it works on other interfaces. Infact, it *also* fails on `ip addr add ... dev tnc0`; indicates something about the way the interface is setup that is problematic

**Comment by deavmi** [comment]
Will continue on this when I have spare time again :)

**Comment by deavmi** [comment]
Found the problem, an mtu of **at least** `1280` is required for IPv6 on Linux, added a warning for this

**Comment by deavmi** [comment]
> Found the problem, an mtu of **at least** `1280` is required for IPv6 on Linux, added a warning for this

Fixing this means I can also technically remove the code _I just_ added for adding link-local as now one is added by the kernel automagically (since meeting the mtu requirement)

**Comment by deavmi** [comment]
> > Found the problem, an mtu of **at least** `1280` is required for IPv6 on Linux, added a warning for this
> 
> Fixing this means I can also technically remove the code _I just_ added for adding link-local as now one is added by the kernel automagically (since meeting the mtu requirement)

Done :heavy_check_mark: . Keeping option to have a no-user-specified mode for Ipv6 addresses, but no longer need to generate and add such a link-local address

**Comment by deavmi** [comment]
Actually, just setting mtu is fine enough

**Comment by deavmi** [comment]
Oki doki, looks to be done. Maybe just some clean up but looks good to me

**Comment by deavmi** [comment]
tncattach

- Now parse IPv6 address and prefix in opt-args

TAP

- Removed parsing from here

**Comment by deavmi** [comment]
I think this just need a little code review now @markqvist

**Comment by markqvist** [comment]
Thanks. Have you verified that this is still working correctly with both TUN and TAP devices while not using IPv6?

**Comment by deavmi** [comment]
I will test today:

1. TUN v6
2. Non-v6 TUN and TAP

On 19 December 2024 11:34:33 SAST, markqvist ***@***.***> wrote:
>Thanks. Have you verified that this is still working correctly with both TUN and TAP devices while not using IPv6?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/tncattach/pull/16#issuecomment-2553195353
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Comment by deavmi** [comment]
> I will test today: 1. TUN v6 2. Non-v6 TUN and TAP
> […](#)
> On 19 December 2024 11:34:33 SAST, markqvist ***@***.***> wrote: Thanks. Have you verified that this is still working correctly with both TUN and TAP devices while not using IPv6? -- Reply to this email directly or view it on GitHub: [#16 (comment)](https://github.com/markqvist/tncattach/pull/16#issuecomment-2553195353) You are receiving this because you authored the thread. Message ID: ***@***.***>
> ---- Tristan B. Velloza Kildaire Web: https://deavmi.assigned.network BNET IRC: deavmi Email: ***@***.***

TUN v6 :heavy_check_mark: 
TUN v4 :heavy_check_mark: 
TAP v6 :heavy_check_mark: 
TAP v4 :heavy_check_mark:

**Comment by deavmi** [comment]
To be extra precautious you could sqaush merge this PR for easy reverting

**Comment by deavmi** [comment]
> > I will test today: 1. TUN v6 2. Non-v6 TUN and TAP
> > […](#)
> > On 19 December 2024 11:34:33 SAST, markqvist _**@**_._**> wrote: Thanks. Have you verified that this is still working correctly with both TUN and TAP devices while not using IPv6? -- Reply to this email directly or view it on GitHub: [#16 (comment)](https://github.com/markqvist/tncattach/pull/16#issuecomment-2553195353) You are receiving this because you authored the thread. Message ID: _**@**_.**_>
> > ---- Tristan B. Velloza Kildaire Web: https://deavmi.assigned.network BNET IRC: deavmi Email: _**@**_.***
> 
> TUN v6 ✔️ TUN v4 ✔️ TAP v6 ✔️ TAP v4 ✔️

@markqvist

**Comment by deavmi** [comment]
Cleaned up indentation now, if there is any code styling you want me to follow before you merge, then let
me know. I shall happily comply.

**Review by markqvist — APPROVED** [review]

**Comment by markqvist** [comment]
Awesome. Everything looking good. Will be merging this now.

**Comment by markqvist** [comment]
Thanks a lot for your work and initiative on this PR. Great to finally have v6 support in tncattach!

**Comment by deavmi** [comment]
> Thanks a lot for your work and initiative on this PR. Great to finally have v6 support in tncattach!

Technically was always there, basic support but having an option that ups the MTU to the minimum required on Linux is more explicit.

The real addition is that you can add an address now (other than link-local which will automatically be added by the kernel when the MTU is 1280 or above).

Thanks for merging!

**Comment by deavmi** [comment]
One more thing, update the readme.MD with the new optargs usage screen output! :-) 

On 22 December 2024 15:28:21 SAST, markqvist ***@***.***> wrote:
>Thanks a lot for your work and initiative on this PR. Great to finally have v6 support in tncattach!
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/markqvist/tncattach/pull/16#issuecomment-2558457161
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>

----
Tristan B. Velloza Kildaire

Web: https://deavmi.assigned.network
BNET IRC: deavmi
Email: ***@***.***

**Pull request merged**
