### PR TITLE
:sparkles: Add TCP Kiss

### PR DESCRIPTION
**Pull request by valentintintin**
Add the capability to use Kiss TCP connection #2.

I tested with the Direwolf console where I see packets but not in "live". I'll try it soon but I'm confident.

Do what you want with my PR :)

### CODE REVIEW

**Comment by markqvist** [comment]
Looking good! I'll try this out shortly and merge if it works as expected :) Thanks for the pull request!

**Comment by markqvist** [comment]
Thanks for the patch! It's merged now. I changed the option format for KISS TCP a bit, to make it unambiguous, and also changed your bcopy and bzero calls, since they have been deprecated from the POSIX specs in favor of the mem... functions. If there's some specific reason you used the BSD variants that I have missed, please let me know!

I'll test this out with Direwolf over the air now, and if it all seems to work as it should, I'll compile and release it all as version 0.1.8 :)

Oh, and please don't take this the wrong way, just a word of advice, but when you change _all_ the indentation in a file from tabs to spaces, and then do all your changes in the same commit, it's practically impossible for the poor maintainer (eg., me) to see what you changed in the diff. I don't have anything against spaces, but please maybe keep it in a separate commit ;)

**Comment by valentintintin** [comment]
Thanks a lot for the merge !
I did not find the time to test over the air yet but I will !
My projet is an Orange Pi on solar panel connected to Hamnet (2.3 Ghz) and I want a link in UHF. Soon in "prod" I hope.

I'm not a C developer at all (only for hobbies) so do not care for `bcopy`. I'm not aware of deprecated functions :)

Sorry for all indentation. My IDE has certainly formated all files when I commited and I didn't notice it.

**Comment by markqvist** [comment]
Ah, very cool project! No worries with the indent, it just took some more time to get the diff sorted out, just wanted to let you know. All good with the memory functions then!

Please let me know how it goes when you have tested it as well, I am interested in the feedback!

**Comment by markqvist** [comment]
And it's released as version 0.1.8 :) Everything is looking good so far. I tested it over the air with a couple of FTP transfers between one computer running DireWolf and another with an OpenModem.

Let me know if you find any bugs or hiccups.

**Pull request merged**
